version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_data:/var/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432
